# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-killswitch" do
  version "1.12.1"

  on_macos do
    on_intel do
      sha256 "6c2043e042a8f492ee03b18217ec92a9390d599ef41977b4c7df8c5ac143dd15"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "262ab1240db8984bafe7d7b0c13bb2ee3507c0ec80b5ac051c500125b24a6d9d"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4cda0ddbe899f99b540e68d3007c5c0a451cd56f7d78db53542874465c17ed0"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c542d2d83ddb95e516ca2bdcc8a274e1b769871df9e34faf3ff0549e23b483e"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aws-killswitch"
  desc "Stop an AWS account spending, without losing anything"
  homepage "https://github.com/fabiocicerchia/aws-killswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-killswitch"
  manpage "man/aws-killswitch.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/aws-killswitch"
  EOS
end
