# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-killswitch" do
  version "1.12.2"

  on_macos do
    on_intel do
      sha256 "b1680aebdad698f31f1deab3fc5f20b782568aa429e3987358ea8aee231020de"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4500a5db544660f8b6ac6ae17f281da34886c764ff17ce9eb01d231a83690ffc"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb027939dbd9a56ecb89509e7178d1641e90bbf8bb0c6b0c4b1b7a60e25a4116"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f32bee3e0cf18eb8eddec5cf8fab851164c159cc74ae1bd034288162a525ded4"
      url "https://github.com/fabiocicerchia/aws-killswitch/releases/download/v#{version}/aws-killswitch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aws-killswitch"
  desc "Stop an AWS account spending, without losing anything"
  homepage "https://github.com/fabiocicerchia/aws-killswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-killswitch"
  manpage "man/aws-killswitch.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/aws-killswitch"
  EOS
end
