# This file was generated by GoReleaser. DO NOT EDIT.
cask "chicco" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "965a65fac50a877cd2c1dce406c0e8391e75d439f54aa7652f37e0e90e96537e"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9aa7f672dbc31aec46a84be513567bc62175c03313ed566165e398d46447859"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f19bb4c39ea60cb14bc91685186a6ab84f1c8e83dc5c29f9bf0c52e4b9417c8b"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87eba93efc4e45450369ca677e9677642285ce44d1a1a45ed7b583dbab62b5f5"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chicco"
  desc "Local OpenAI- and Anthropic-compatible rotation proxy"
  homepage "https://github.com/fabiocicerchia/chicco"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chicco"
  manpage "man/chicco.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/chicco"
  EOS
end
