# This file was generated by GoReleaser. DO NOT EDIT.
cask "chicco" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4e96c797206a6969941a3e24168bcc6a8c297179d163c62bb69d513dad3ee362"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2daf27bb9b75ed7ff1b8575927d3154ac80957280cc90b959e68537e71351dd9"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c199e641c1331ea55284106d2a9048efec73d829a6552ce4ea9b0f7a725ff98"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4e6a5b9b57d86bbf629fee750727589f751fa7ffac92b157beccb18d5aed2c7"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chicco"
  desc "Local OpenAI- and Anthropic-compatible rotation proxy"
  homepage "https://github.com/fabiocicerchia/chicco"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chicco"
  manpage "man/chicco.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/chicco"
  EOS
end
