# This file was generated by GoReleaser. DO NOT EDIT.
cask "chicco" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "a90417fc038442a504f07df9b61d87694398fcd675f07532fd667e66546ee77c"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da4864364c97bf2f2f965b2761965f110c218354e23fce59649c29bfde91b7cd"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4453cbd10408de418282001510b22a6ffd0892b0875a1c73c86af31a3f705ecf"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "817b187af822c95a11c2c0f529f9fe36b43d579225f3fdbe536dbe42fd709fe4"
      url "https://github.com/fabiocicerchia/chicco/releases/download/v#{version}/chicco_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chicco"
  desc "Local OpenAI- and Anthropic-compatible rotation proxy"
  homepage "https://github.com/fabiocicerchia/chicco"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chicco"
  manpage "man/chicco.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/chicco"
  EOS
end
