# This file was generated by GoReleaser. DO NOT EDIT.
cask "dark-canary" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "a88af09b6fdaa83fdab296a32228649c43d843d54f725f6a0fa6aaa85346485f"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7dfd9ce1c71e702187c659a8ba994b0cc67a0781648c7bbf2556f0a3f874394a"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0111f5521ceed78bbc64a65111745919bb3df50902679c6c5a7c71ee52a1fa8d"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d0b6aa2b86aba49e827d01ca7a9bc18af3f68f7f6e085d48248af406620ad8e"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dark-canary"
  desc "Mirror traffic to a shadow deployment and diff the responses"
  homepage "https://github.com/fabiocicerchia/dark-canary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dark-canary"
  manpage "man/dark-canary.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/dark-canary"
  EOS
end
