# This file was generated by GoReleaser. DO NOT EDIT.
cask "dark-canary" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "9076516ed68f0363fcf88b023b3cb9f9a24170a8905c6f7155e328974f68b453"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14314841c3b1c3e315f21610069ed7b282e0c2352691898dd0e1246caff7eb7e"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28d676577e5ab2ea7ae8f42861f70a79dff113f086bba0f5f0fa0c48ec4377ce"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd500220aca6e0bc5f8831f536aac0dc3fe24bcbd365a4d42fcb8b9991507ee7"
      url "https://github.com/fabiocicerchia/dark-canary/releases/download/v#{version}/dark-canary_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dark-canary"
  desc "Mirror traffic to a shadow deployment and diff the responses"
  homepage "https://github.com/fabiocicerchia/dark-canary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dark-canary"
  manpage "man/dark-canary.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/dark-canary"
  EOS
end
