# This file was generated by GoReleaser. DO NOT EDIT.
cask "expiry-radar" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "5049aa159ac2b94c37bec08c67223a5ca4d97161a7d37f7632a75a0b11ab613f"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7abcee0afb922e874cf8ece47ffe35a3b834409463a233694bfb29bdad8ee393"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c7d48bdb3a22b5ac7a46576b88c3d725a372f186507ae98d462d902b1ee29d2"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e6095394ef6137bd7a2517028aaa2abbb45a0f5b645d55701a399450deed4af"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "expiry-radar"
  desc "One inventory of everything that expires, ranked by blast radius"
  homepage "https://github.com/fabiocicerchia/expiry-radar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "expiry-radar"
  manpage "man/expiry-radar.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/expiry-radar"
  EOS
end
