# This file was generated by GoReleaser. DO NOT EDIT.
cask "expiry-radar" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "cf5a3ec90293037cf4ef6daeb2f9ab208d1ec8cc810752c5f4eba1fc98d48a9b"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "938e1cc66b5ad0d1831787252156671522def54dd196e6dc393c74ec2752c30c"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80442d189a5d24a6826fdca6ef6624224b5d1db5f5a759c5658d6041a881ea93"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eca4d1634f56d9e0df394892276e6d03682b0f5dd859e3b133d481e9ddd8aac9"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "expiry-radar"
  desc "One inventory of everything that expires, ranked by blast radius"
  homepage "https://github.com/fabiocicerchia/expiry-radar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "expiry-radar"
  manpage "man/expiry-radar.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/expiry-radar"
  EOS
end
