# This file was generated by GoReleaser. DO NOT EDIT.
cask "expiry-radar" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "2134bc72d0cddd8cf1a4f42f261cfc1895bae740646eb47b5d9829a83f2bd614"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c863017f7e54343a29e00e1ebec378f6f01c1de541d78872b217beb968fdf844"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f0e16d95a5884ceec8cb2ba09a20817ed6b6e2f9b2a9bd997e78587f324bb05"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e54a9d0858fceef28697f5f39ca5f6dd4ee502e11110d921302e240d1170a54a"
      url "https://github.com/fabiocicerchia/expiry-radar/releases/download/v#{version}/expiry-radar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "expiry-radar"
  desc "One inventory of everything that expires, ranked by blast radius"
  homepage "https://github.com/fabiocicerchia/expiry-radar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "expiry-radar"
  manpage "man/expiry-radar.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/expiry-radar"
  EOS
end
