# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-fit" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "8b4de840161714b7843fa8dbcedda014cdb356e2fa4c1e222889c3db1c4bcff1"
      url "https://github.com/fabiocicerchia/llm-fit/releases/download/v#{version}/llm-fit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d20754c75ca7aef2a55eed2637309c1daacc524cf766af38a73a0c205efacc6e"
      url "https://github.com/fabiocicerchia/llm-fit/releases/download/v#{version}/llm-fit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac7f7139274004f23113d8ab1f29eb5c05cdb49455f640300368b25b052adcb0"
      url "https://github.com/fabiocicerchia/llm-fit/releases/download/v#{version}/llm-fit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66124076b2a0703b649cdaefe2c1aac9d1bd14d54480842f74e59f8777316ff5"
      url "https://github.com/fabiocicerchia/llm-fit/releases/download/v#{version}/llm-fit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llm-fit"
  desc "Which LLMs this machine can run, and how fast"
  homepage "https://github.com/fabiocicerchia/llm-fit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-fit"
  manpage "man/llm-fit.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/llm-fit"
  EOS
end
