# This file was generated by GoReleaser. DO NOT EDIT.
cask "sci-disclose" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "a6bdc223866557973e65f5fbf716dd47031a1d75c47b299fa50c9274036bbd83"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8dec32c122f483d6a314ad092db3cd78e0f914d8bc6d6537aa053ef78a3db5f"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "526856dc34176b1eaa01ad6942992edbf0507a743c18bc7709d4c12f646ecdb2"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f03abd4b7c66a7a1580b4734fe58d2dba1cfe4669b0897bf45b41b279c93a26c"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sci-disclose"
  desc "Software Carbon Intensity (SCI) from the command line"
  homepage "https://github.com/fabiocicerchia/sci-disclose"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sci-disclose"
  manpage "man/sci-disclose.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/sci"
  EOS
end
