# This file was generated by GoReleaser. DO NOT EDIT.
cask "sci-disclose" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "eb9c95d60749d07d25a99f94027f7b10fb320dfcad293cd37e719b2c51ab9c6c"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbff0336fa0d2d3e2fbf4d7d28eb515a5b30b38efb129afadb9c8935dc4081b5"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a68c86cc58ac321fb7787124838e6c21d32d8cf1e27f787aa050a87a282701a6"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "254d6a8f19931b342784c4e9247eed687daca6d63e319a6c8a7be154f20b4cb3"
      url "https://github.com/fabiocicerchia/sci-disclose/releases/download/v#{version}/sci-disclose_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sci-disclose"
  desc "Software Carbon Intensity (SCI) from the command line"
  homepage "https://github.com/fabiocicerchia/sci-disclose"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sci-disclose"
  manpage "man/sci-disclose.1"

  # No zap stanza required

  caveats <<~EOS
    macOS quarantines binaries it cannot verify. On first run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/sci"
  EOS
end
