# Generated by scripts/render_formulae.py — do not edit by hand.
class BackupVerify < Formula
  include Language::Python::Virtualenv

  desc "Prove that your backups restore, on a schedule"
  homepage "https://github.com/fabiocicerchia/backup-verify"
  url "https://github.com/fabiocicerchia/backup-verify/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "74e20dcdace5eb0e6e9894ea914a32060dcd1ea0f4697c2aa89d014b8591c2b9"
  license "Apache-2.0"

  depends_on "python@3.13"

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f"
  end

  def install
    virtualenv_install_with_resources
    man1.install "man/backup-verify.1"
  end

  test do
    assert_match "backup-verify", shell_output("#{bin}/backup-verify --help 2>&1", 0)
  end
end
