# Generated by scripts/render_formulae.py — do not edit by hand.
class Chaosbox < Formula
  desc "Small, time-boxed chaos experiments"
  homepage "https://github.com/fabiocicerchia/chaos-toolbox"
  url "https://github.com/fabiocicerchia/chaos-toolbox/archive/refs/tags/v2.0.2.tar.gz"
  sha256 "cde125011bb28995b62a423ad6ba89f36b8a47f1175bce649ff9d45b9575101d"
  license "Apache-2.0"

  depends_on :linux
  depends_on "stress-ng"

  def install
    bin.install "chaosbox"
    man1.install "man/chaosbox.1"
  end

  def caveats
    <<~EOS
      Network experiments need tc (iproute2) and CAP_NET_ADMIN.
      `chaosbox kill` needs docker or kubectl, depending on --mode.
    EOS
  end

  test do
    assert_match "chaosbox", shell_output("#{bin}/chaosbox --help 2>&1", 0)
  end
end
