# Generated by scripts/render_formulae.py — do not edit by hand.
class Chaosbox < Formula
  desc "Small, time-boxed chaos experiments"
  homepage "https://github.com/fabiocicerchia/chaos-toolbox"
  url "https://github.com/fabiocicerchia/chaos-toolbox/archive/refs/tags/v2.0.3.tar.gz"
  sha256 "ff6adf60926ff0a877c483f17bea72fbe676a685804d7e0b174858e243d7ad5c"
  license "Apache-2.0"

  depends_on :linux
  depends_on "stress-ng"

  def install
    bin.install "chaosbox"
    man1.install "man/chaosbox.1"
  end

  def caveats
    <<~EOS
      Network experiments need tc (iproute2) and CAP_NET_ADMIN.
      `chaosbox kill` needs docker or kubectl, depending on --mode.
    EOS
  end

  test do
    assert_match "chaosbox", shell_output("#{bin}/chaosbox --help 2>&1", 0)
  end
end
