# Generated by scripts/render_formulae.py — do not edit by hand.
class ClaudeKeepalive < Formula
  include Language::Python::Virtualenv

  desc "Run claude and auto-resume after a usage-limit reset"
  homepage "https://github.com/fabiocicerchia/claude-keepalive"
  url "https://github.com/fabiocicerchia/claude-keepalive/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "cfc9b3d80213cb0fcd8e2722d304a4051ff97d9cefaa9b409bca425d83d9ffd8"
  license "MIT"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/claude-keepalive.1"
  end

  test do
    assert_match "claude-keepalive", shell_output("#{bin}/claude-keepalive --help 2>&1", 0)
  end
end
