# Generated by scripts/render_formulae.py — do not edit by hand.
class ClaudeKeepalive < Formula
  include Language::Python::Virtualenv

  desc "Run claude and auto-resume after a usage-limit reset"
  homepage "https://github.com/fabiocicerchia/claude-keepalive"
  url "https://github.com/fabiocicerchia/claude-keepalive/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "d7420415334b189dd0d493e31ada9e10281fd7a1dddb12f0161026e5e283e1fc"
  license "MIT"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/claude-keepalive.1"
  end

  test do
    assert_match "claude-keepalive", shell_output("#{bin}/claude-keepalive --help 2>&1", 0)
  end
end
