# Generated by scripts/render_formulae.py — do not edit by hand.
class ClusterCollect < Formula
  desc "Gather a Kubernetes incident support bundle"
  homepage "https://github.com/fabiocicerchia/cluster-info-collector"
  url "https://github.com/fabiocicerchia/cluster-info-collector/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "b60beb7046baa592b74025fd85575ec77e5d9ddea12f82e27640d3680efa3d8b"
  license "Apache-2.0"

  depends_on "kubernetes-cli"

  def install
    bin.install "cluster-collect"
    (prefix/"lib/cluster-info-collector").install "lib.sh"
    man1.install "man/cluster-collect.1"
  end

  def caveats
    <<~EOS
      Set BUNDLE_S3_URI to upload the bundle; that path needs the AWS CLI.
    EOS
  end

  test do
    assert_predicate bin/"cluster-collect", :executable?
    assert_match "cluster-collect", (man1/"cluster-collect.1").read
  end
end
