# Generated by scripts/render_formulae.py — do not edit by hand.
class CronTranslate < Formula
  include Language::Python::Virtualenv

  desc "Cron expressions in human terms"
  homepage "https://github.com/fabiocicerchia/cron-translate"
  url "https://github.com/fabiocicerchia/cron-translate/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "f213ccbbed015721f9e12517585bae33f7d3d36910d6b8f7b552daedc240c871"
  license "Apache-2.0"

  depends_on "python@3.13"

  resource "croniter" do
    url "https://files.pythonhosted.org/packages/37/57/2e2a65aee2a70483cb28e2b7e15a072d00a523207593b44400d4717bb100/croniter-6.2.4.tar.gz"
    sha256 "fc124f751b1b04805c2a04b061898b436b45ab2320b045e1e052ea895de65189"
  end

  def install
    virtualenv_install_with_resources
    man1.install "man/cron-translate.1"
  end

  test do
    assert_match "cron-translate", shell_output("#{bin}/cron-translate --help 2>&1", 0)
  end
end
