# Generated by scripts/render_formulae.py — do not edit by hand.
class DockerfileHardener < Formula
  include Language::Python::Virtualenv

  desc "Rewrite a Dockerfile to best practice and show the diff"
  homepage "https://github.com/fabiocicerchia/dockerfile-hardener"
  url "https://github.com/fabiocicerchia/dockerfile-hardener/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "be54a26a87df9f826cdd69690b567ed0232bbdf1406d669da624c6b59e0495fb"
  license "Apache-2.0"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/dockerfile-hardener.1"
  end

  test do
    assert_match "dockerfile-hardener", shell_output("#{bin}/dockerfile-hardener --help 2>&1", 0)
  end
end
