# Generated by scripts/render_formulae.py — do not edit by hand.
class DockerfileHardener < Formula
  include Language::Python::Virtualenv

  desc "Rewrite a Dockerfile to best practice and show the diff"
  homepage "https://github.com/fabiocicerchia/dockerfile-hardener"
  url "https://github.com/fabiocicerchia/dockerfile-hardener/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "cf74b53fc0e475d475490968bdd77563a412373f1bc753758d982a7980ba8cba"
  license "Apache-2.0"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/dockerfile-hardener.1"
  end

  test do
    assert_match "dockerfile-hardener", shell_output("#{bin}/dockerfile-hardener --help 2>&1", 0)
  end
end
