# Generated by scripts/render_formulae.py — do not edit by hand.
class Envdiff < Formula
  include Language::Python::Virtualenv

  desc "Diff environment variables between two environments, safely"
  homepage "https://github.com/fabiocicerchia/envdiff"
  url "https://github.com/fabiocicerchia/envdiff/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "7537cc74c4408dd8ed2779a2a5a1861799ca2abcefaece791fee911d544a1a59"
  license "Apache-2.0"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/envdiff.1"
  end

  test do
    assert_match "envdiff", shell_output("#{bin}/envdiff --help 2>&1", 0)
  end
end
