# Generated by scripts/render_formulae.py — do not edit by hand.
class InitToolkit < Formula
  desc "Readiness and health-check probes for init containers"
  homepage "https://github.com/fabiocicerchia/init-toolkit"
  url "https://github.com/fabiocicerchia/init-toolkit/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "344c655aacc2f2c4d99725599ca14acd4721d5e2fce9304bddac70d11055e8ff"
  license "Apache-2.0"


  def install
    bin.install "bin/wait-for"
    bin.install "bin/healthcheck-http"
    bin.install "bin/healthcheck-tcp"
    man1.install "man/wait-for.1"
    man1.install "man/healthcheck-http.1"
    man1.install "man/healthcheck-tcp.1"
  end

  test do
    assert_match "wait-for", shell_output("#{bin}/wait-for --help 2>&1", 0)
  end
end
