# Generated by scripts/render_formulae.py — do not edit by hand.
class InitToolkit < Formula
  desc "Readiness and health-check probes for init containers"
  homepage "https://github.com/fabiocicerchia/init-toolkit"
  url "https://github.com/fabiocicerchia/init-toolkit/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "54cb1d6f4ccf377a94abff85b94aeeb99aebc90793a8e85e829f3c8a51c348a1"
  license "Apache-2.0"


  def install
    bin.install "bin/wait-for"
    bin.install "bin/healthcheck-http"
    bin.install "bin/healthcheck-tcp"
    man1.install "man/wait-for.1"
    man1.install "man/healthcheck-http.1"
    man1.install "man/healthcheck-tcp.1"
  end

  test do
    assert_match "wait-for", shell_output("#{bin}/wait-for --help 2>&1", 0)
  end
end
