# Generated by scripts/render_formulae.py — do not edit by hand.
class K8sRightsizerReport < Formula
  include Language::Python::Virtualenv

  desc "Turn live Kubernetes usage into PR-ready requests and limits"
  homepage "https://github.com/fabiocicerchia/k8s-rightsizer-report"
  url "https://github.com/fabiocicerchia/k8s-rightsizer-report/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "694ea59dfb389974ec9d695b705a7ee231a58bfa3a43df6739ccd7072de4521b"
  license "Apache-2.0"

  depends_on "python@3.13"
  depends_on "kubernetes-cli"

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f"
  end

  def install
    virtualenv_install_with_resources
    man1.install "man/k8s-rightsizer-report.1"
  end

  test do
    assert_match "k8s-rightsizer-report", shell_output("#{bin}/k8s-rightsizer-report --help 2>&1", 0)
  end
end
