# Generated by scripts/render_formulae.py — do not edit by hand.
class Netreport < Formula
  desc "One-shot connectivity snapshot for incident notes"
  homepage "https://github.com/fabiocicerchia/mtr-toolbox"
  url "https://github.com/fabiocicerchia/mtr-toolbox/archive/refs/tags/v1.3.0.tar.gz"
  sha256 "afc07175becb949afe4eea07fd82392a188d7cbd913a55700202605482e9ea7c"
  license "Apache-2.0"

  depends_on :linux
  depends_on "mtr"

  def install
    bin.install "netreport"
    man1.install "man/netreport.1"
  end

  def caveats
    <<~EOS
      Uses ip(8) from iproute2 and dig(1); both are expected on the host.
    EOS
  end

  test do
    assert_predicate bin/"netreport", :executable?
    assert_match "netreport", (man1/"netreport.1").read
  end
end
