# Generated by scripts/render_formulae.py — do not edit by hand.
class Netreport < Formula
  desc "One-shot connectivity snapshot for incident notes"
  homepage "https://github.com/fabiocicerchia/mtr-toolbox"
  url "https://github.com/fabiocicerchia/mtr-toolbox/archive/refs/tags/v1.3.2.tar.gz"
  sha256 "8fce89e908bc058c6a33c3e2ba314708ab4cfcc08c066bf5b41e9d8f97bfb40b"
  license "Apache-2.0"

  depends_on :linux
  depends_on "mtr"

  def install
    bin.install "netreport"
    man1.install "man/netreport.1"
  end

  def caveats
    <<~EOS
      Uses ip(8) from iproute2 and dig(1); both are expected on the host.
    EOS
  end

  test do
    assert_predicate bin/"netreport", :executable?
    assert_match "netreport", (man1/"netreport.1").read
  end
end
