# Generated by scripts/render_formulae.py — do not edit by hand.
class Netreport < Formula
  desc "One-shot connectivity snapshot for incident notes"
  homepage "https://github.com/fabiocicerchia/mtr-toolbox"
  url "https://github.com/fabiocicerchia/mtr-toolbox/archive/refs/tags/v1.3.1.tar.gz"
  sha256 "c8be9186c53db8010c92b73661d07ca9e6870419b4b77f4a92f6bed63b0adbff"
  license "Apache-2.0"

  depends_on :linux
  depends_on "mtr"

  def install
    bin.install "netreport"
    man1.install "man/netreport.1"
  end

  def caveats
    <<~EOS
      Uses ip(8) from iproute2 and dig(1); both are expected on the host.
    EOS
  end

  test do
    assert_predicate bin/"netreport", :executable?
    assert_match "netreport", (man1/"netreport.1").read
  end
end
