# Generated by scripts/render_formulae.py — do not edit by hand.
class RbacAudit < Formula
  include Language::Python::Virtualenv

  desc "Readable RBAC reports from a live Kubernetes cluster"
  homepage "https://github.com/fabiocicerchia/rbac-auditor"
  url "https://github.com/fabiocicerchia/rbac-auditor/archive/refs/tags/v2.0.1.tar.gz"
  sha256 "bcf90a494707cd61344c9552c32d997a61206d40f30a5d45c36e07bac30980de"
  license "Apache-2.0"

  depends_on "python@3.13"
  depends_on "kubernetes-cli"

  def install
    virtualenv_install_with_resources
    man1.install "man/rbac-audit.1"
  end

  test do
    assert_match "rbac-audit", shell_output("#{bin}/rbac-audit --help 2>&1", 0)
  end
end
