# Generated by scripts/render_formulae.py — do not edit by hand.
class RbacAudit < Formula
  include Language::Python::Virtualenv

  desc "Readable RBAC reports from a live Kubernetes cluster"
  homepage "https://github.com/fabiocicerchia/rbac-auditor"
  url "https://github.com/fabiocicerchia/rbac-auditor/archive/refs/tags/v1.3.1.tar.gz"
  sha256 "bd3e58f5f188abc163174497777b9d43ea5bb29c9521af74e7bcac89c5235d0b"
  license "Apache-2.0"

  depends_on "python@3.13"
  depends_on "kubernetes-cli"

  def install
    virtualenv_install_with_resources
    man1.install "man/rbac-audit.1"
  end

  test do
    assert_match "rbac-audit", shell_output("#{bin}/rbac-audit --help 2>&1", 0)
  end
end
