# Generated by scripts/render_formulae.py — do not edit by hand.
class RbacAudit < Formula
  include Language::Python::Virtualenv

  desc "Readable RBAC reports from a live Kubernetes cluster"
  homepage "https://github.com/fabiocicerchia/rbac-auditor"
  url "https://github.com/fabiocicerchia/rbac-auditor/archive/refs/tags/v2.0.0.tar.gz"
  sha256 "a1cda7f2ee59e929a6a2f9f4b4b00640b868bc14d395a2699bf864377d7cab1c"
  license "Apache-2.0"

  depends_on "python@3.13"
  depends_on "kubernetes-cli"

  def install
    virtualenv_install_with_resources
    man1.install "man/rbac-audit.1"
  end

  test do
    assert_match "rbac-audit", shell_output("#{bin}/rbac-audit --help 2>&1", 0)
  end
end
