# Generated by scripts/render_formulae.py — do not edit by hand.
class Scoville < Formula
  include Language::Python::Virtualenv

  desc "Rate how dangerous a shell command is, before you run it"
  homepage "https://github.com/fabiocicerchia/scoville"
  url "https://github.com/fabiocicerchia/scoville/archive/refs/tags/v0.4.2.tar.gz"
  sha256 "44a6ee08aa98106c6be4cf04134524336197fff11eba87aff03601be91087a4b"
  license "Apache-2.0"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/scoville.1"
  end

  test do
    assert_match "scoville", shell_output("#{bin}/scoville --help 2>&1", 0)
  end
end
