# Generated by scripts/render_formulae.py — do not edit by hand.
class ToilAudit < Formula
  include Language::Python::Virtualenv

  desc "Quantify the cost of babysitting CI/CD, in euros"
  homepage "https://github.com/fabiocicerchia/toil-audit"
  url "https://github.com/fabiocicerchia/toil-audit/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "df8354c54c2fc389ed1df0f42e6fa9ef1a04af1e26b7ef8da7aa22e96446c54b"
  license "Apache-2.0"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
    man1.install "man/toil-audit.1"
  end

  test do
    assert_match "toil-audit", shell_output("#{bin}/toil-audit --help 2>&1", 0)
  end
end
