#!/usr/bin/env python3
"""Regenerate Formula/*.rb from tools.json.

Each formula is pinned to its tool's latest release: the source tarball, its
sha256, and the files that release actually contains. A tool whose latest
release does not yet carry the binaries and man pages tools.json expects is
skipped with a note rather than rendered into something broken — the next run
picks it up once it releases.

Run with no arguments. GITHUB_TOKEN is used when set, purely for rate limits.
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import sys
import tarfile
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OWNER = "fabiocicerchia"
UA = {"User-Agent": "homebrew-tap-renderer"}


def get(url: str, token_ok: bool = True) -> bytes:
    headers = dict(UA)
    tok = os.environ.get("GITHUB_TOKEN")
    if tok and token_ok:
        headers["Authorization"] = f"Bearer {tok}"
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=60) as r:
        return r.read()


def latest_tag(repo: str) -> str | None:
    try:
        d = json.loads(get(f"https://api.github.com/repos/{OWNER}/{repo}/releases/latest"))
    except urllib.error.HTTPError:
        return None
    return d.get("tag_name")


def camel(name: str) -> str:
    """Homebrew derives the class name from the file name this way."""
    return "".join(p.capitalize() for p in name.replace("_", "-").split("-"))


def pypi_sdist(pkg: str) -> tuple[str, str, str]:
    """Latest sdist url, sha256 and version for a PyPI package."""
    d = json.loads(get(f"https://pypi.org/pypi/{pkg}/json", token_ok=False))
    for f in d["urls"]:
        if f["packagetype"] == "sdist":
            return f["url"], f["digests"]["sha256"], d["info"]["version"]
    raise SystemExit(f"{pkg}: no sdist on PyPI")


def render(tool: dict, tag: str, sha: str, members: set[str]) -> str | None:
    """The formula text, or None when the release is missing expected files."""
    # A python tool's command is a console script pip generates at install
    # time, so the repo has no file by that name — what must be present is the
    # packaging metadata. A shell tool ships the executable itself.
    if tool["kind"] == "python":
        want = ["pyproject.toml"] + list(tool.get("mans", []))
    else:
        want = list(tool["binaries"]) + list(tool.get("mans", [])) \
            + list(tool.get("extra_files", {}))
    missing = [w for w in want if w not in members]
    if missing:
        print(f"  skip {tool['formula']}: {tag} has no {', '.join(missing)}")
        return None

    L = [f"# Generated by scripts/render_formulae.py — do not edit by hand.",
         f"class {camel(tool['formula'])} < Formula"]
    if tool["kind"] == "python":
        L.append("  include Language::Python::Virtualenv")
        L.append("")
    L += [f'  desc "{tool["desc"]}"',
          f'  homepage "https://github.com/{OWNER}/{tool["repo"]}"',
          f'  url "https://github.com/{OWNER}/{tool["repo"]}/archive/refs/tags/{tag}.tar.gz"',
          f'  sha256 "{sha}"',
          f'  license "{tool["license"]}"',
          ""]

    if tool.get("linux_only"):
        L.append("  depends_on :linux")
    if tool["kind"] == "python":
        L.append('  depends_on "python@3.13"')
    for d in tool.get("depends", []):
        L.append(f'  depends_on "{d}"')
    L.append("")

    for pkg in tool.get("resources", []):
        url, rsha, ver = pypi_sdist(pkg)
        L += [f'  resource "{pkg}" do',
              f'    url "{url}"',
              f'    sha256 "{rsha}"',
              "  end", ""]

    L.append("  def install")
    if tool["kind"] == "python":
        L.append("    virtualenv_install_with_resources")
    else:
        for b in tool["binaries"]:
            L.append(f'    bin.install "{b}"')
        for src, dst in tool.get("extra_files", {}).items():
            L.append(f'    (prefix/"{dst}").install "{src}"')
    for m in tool.get("mans", []):
        L.append(f'    man1.install "{m}"')
    L += ["  end", ""]

    if tool.get("caveats"):
        L += ["  def caveats", "    <<~EOS"]
        L += [f"      {line}" for line in tool["caveats"].splitlines()]
        L += ["    EOS", "  end", ""]

    probe = tool.get("test_binary") or pathlib.PurePosixPath(tool["binaries"][0]).name
    L.append("  test do")
    if tool["kind"] == "python" or tool.get("help_flag"):
        L.append(f'    assert_match "{probe}", shell_output("#{{bin}}/{probe} --help 2>&1", 0)')
    else:
        # These do not take --help: they would read it as a host, a namespace or
        # a URL and go and do the thing. Check what was installed instead.
        L.append(f'    assert_predicate bin/"{probe}", :executable?')
        if tool.get("mans"):
            man = pathlib.PurePosixPath(tool["mans"][0]).name
            L.append(f'    assert_match "{probe}", (man1/"{man}").read')
    L += ["  end", "end"]
    return "\n".join(L) + "\n"


def main() -> int:
    spec = json.loads((ROOT / "tools.json").read_text())
    out = ROOT / "Formula"
    out.mkdir(exist_ok=True)
    written, skipped = [], []

    for tool in spec["tools"]:
        tag = latest_tag(tool["repo"])
        if not tag:
            print(f"  skip {tool['formula']}: no release yet")
            skipped.append(tool["formula"])
            continue
        url = f"https://github.com/{OWNER}/{tool['repo']}/archive/refs/tags/{tag}.tar.gz"
        blob = get(url, token_ok=False)
        sha = hashlib.sha256(blob).hexdigest()

        tmp = ROOT / ".tarball.tmp"
        tmp.write_bytes(blob)
        with tarfile.open(tmp) as tf:
            # GitHub prefixes every entry with "<repo>-<version>/".
            members = {m.name.split("/", 1)[1] for m in tf.getmembers() if "/" in m.name}
        tmp.unlink()

        text = render(tool, tag, sha, members)
        if text is None:
            skipped.append(tool["formula"])
            continue
        (out / f"{tool['formula']}.rb").write_text(text)
        written.append(f"{tool['formula']} {tag}")

    print(f"\nwrote {len(written)}: {', '.join(written)}")
    if skipped:
        print(f"pending a release: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
